### PR TITLE
Fixed check for proxy configuration

### PR DESCRIPTION
**Pull request by BrainStone**
`-z` checks if the variable is empty, `-n` checks if it's not empty.

### CODE REVIEW

**Comment by drtyhlpr** [comment]
hm maybe we can simply add  a variable KEEP_APT_PROXY=false or something like that. hm the more I think about it ... well maybe we need a HTTP_PROXY parameter that set the "system-wide" http_proxy (via environment variable) inside the generated rpi image.

**Comment by burnbabyburn** [comment]
> "system-wide" http_proxy (via environment variable) inside the generated rpi image.

I never expected `APT_PROXY `to be persistent in the created image. Thats why i like the idea of having two variables for that. 
E.g. 

1. my build system needs a proxy to get packages ( or it should use apt-cacher), but my RPI don't -> Set `DEBOOTSTRAP_PROXY`
or
2. my build system shall not use apt-cacher but my pi needs a proxy -> `APT_PROXY`

it would be quite confusing if we fix the` if [ -z "$APT_PROXY" ] ; then` check and suddenly have a APT::PROXY configuration in our image.

**Comment by drtyhlpr** [comment]
yup I agree burnbabyburn. but it should also be considered it would nice to have a "include my default proxy in the generated image" if you create and run a rpi image inside a network where you are forced to use a proxy to get internet connection (the bootstrapping system and the rpi) etc

**Comment by burnbabyburn** [comment]
>  "include my default proxy in the generated image"
using a "make proxy persistent flag" or "using two vars" for that task - in the end it doesn't matter that much :) The feature is the nice thing and thus thx for the pull!

**Comment by drtyhlpr** [comment]
should be fixed with https://github.com/drtyhlpr/rpi23-gen-image/commit/782219f11ef8f5c5121c3b6a7bce6235f0ee70c1

**Pull request closed without merging**
