### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by burnbabyburn**
PLS WAIT 'TILL MERGE
These are the changes i made so far. i successfully build:
```
RPI3+cryptfs 64bit
RPI3P+cryptfs 64bit
RPI3+cryptfs 32bit
```

i used my default template:
```
SET_ARCH=32
RPI_MODEL=3P
RELEASE=buster

DEFLOCAL=de_DE.UTF-8
XKB_LAYOUT=de

BUILD_KERNEL=true
KERNEL_BRANCH=rpi-4.14.y
KERNEL_CCACHE=true
#KERNEL_ZSWAP=true
#KERNEL_VIRT=true
#KERNEL_NF=true
#KERNEL_BPF=true

ENABLE_CRYPTFS=true
CRYPTFS_PASSWORD=password

HOSTNAME=pihole
USER_NAME=user
USER_PASSWORD=password
PASSWORD=password

ENABLE_CONSOLE=false
ENABLE_VIDEOCORE=true
ENABLE_IPTABLES=true
ENABLE_I2C=true
ENABLE_SPI=true
ENABLE_NONFREE=true
ENABLE_WIRELESS=true
ENABLE_SOUND=true
ENABLE_MINGPU=true
ENABLE_DBUS=true
ENABLE_IFNAMES=false
ENABLE_UBOOT=false
ENABLE_SPLITFS=false
ENABLE_INITRAMFS=true
ENABLE_SYSVINIT=true
ENABLE_ROOT=false
ENABLE_MINBASE=false
ENABLE_XORG=false
ENABLE_RSYSLOG=true
ENABLE_HWRANDOM=true
ENABLE_IPV6=true
ENABLE_DHCP=true

ENABLE_REDUCE=true
REDUCE_APT=true
REDUCE_DOC=true
REDUCE_MAN=true
REDUCE_VIM=false
REDUCE_BASH=false
REDUCE_HWDB=false
REDUCE_SSHD=false
REDUCE_LOCALE=false

SSH_LIMIT_USERS=true

#KERNELSRC_DIR=/home/helge/linux
RPI_FIRMWARE_DIR=/home/helge/firmware
UBOOTSRC_DIR=/home/helge/u-boot
VIDEOCORESRC_DIR=/home/helge/userland

APT_INCLUDES=busybox,kbd,net-tools,wireless-tools,git,crda,wireless-regdb,build-essential

IMAGE_NAME=RPI-3P-64bit
#CHROOT_SCRIPTS=/home/helge/rpi23-gen-image/chroot_scripts
#APT_SERVER=mirror.netcologne.de
```

### CODE REVIEW

**Comment by burnbabyburn** [comment]
p.s. maybe we should add a dev branch?

**Comment by drtyhlpr** [comment]
hm shit no the above config is not working. i got my serial interface and ll try to debug the cause of this strange problem .... argh

**Comment by drtyhlpr** [comment]
please updade the README ENABLE_CONSOLE RPi 0/1/2/4  so I dont get a "This branch has conflicts that must be resolved"

**Comment by drtyhlpr** [comment]
for testing please dont use an advanced template. 1st just make sure the default templates rpi2* rpi* work pls.

**Comment by drtyhlpr** [comment]
no serial output with the above configuration. hmmm ... no what to debug the kernel panic ahhhh

**Comment by drtyhlpr** [comment]
no serial output with the above configuration. hmmm ... no what to debug the kernel panic ahhhh

**Comment by burnbabyburn** [comment]
whats's githubs problem with that line :/

**Comment by drtyhlpr** [comment]
> whats's githubs problem with that line :/

hehe well I think you somehow got another text at the ENABLE_CONSOLE. I dont know. here is the conflict:

```
#### Basic system features:
##### `ENABLE_CONSOLE`=true
<<<<<<< 0
Enable serial console interface. Recommended if no monitor or keyboard is connected to the RPi2/3. In case of problems fe. if the network (auto) configuration failed - the serial console can be used to access the system.
On `RPI_MODEL= 0,3,3P` - Bluetooth gets auto enabled if `ENABLE_CONSOLE` and `ENABLE_UBOOT` are set to `false` 
=======
Enable serial console interface. Recommended if no monitor or keyboard is connected to the RPi 0/1/2/3. In case of problems fe. if the network (auto) configuration failed - the serial console can be used to access the system.
>>>>>>> master
```

**Comment by drtyhlpr** [comment]
please do not enable bluetooth (and disable console tty) or wireless by default please.

**Comment by drtyhlpr** [comment]
hm I can not rely believe its the cause of all my troubles today. but setting `ENABLE_CONSOLE=false` now creates bootable images +

**Comment by burnbabyburn** [comment]
atm it's either bluetooth or serial set via ENABLE_CONSOLE. so we need a new var ENABLE_BLUETOOTH for that

**Comment by drtyhlpr** [comment]
please tell me if I should merge this pull now. I am quite bussy aggain.

yeah I would love to have CONSOLE as default. also for debugging purposes if you ENABLE_BLUETOOTH you loose the CONSOLE support of course

**Comment by burnbabyburn** [comment]
> yeah I would love to have CONSOLE as default. also for debugging purposes if you ENABLE_BLUETOOTH you loose the CONSOLE support of course
Actually you can use bluetooth and serial at the same time on pi.

**Pull request merged**
