### PR TITLE
Initial Dropbear

### PR DESCRIPTION
**Pull request by burnbabyburn**
Adding Buildbox info
Adding Initial Dropbear support (initramfs-hook broken, keys get added to dropbear authorized_keys and it is included in initramfs)
added script example
added some recommended packages for debian

### CODE REVIEW

**Comment by burnbabyburn** [comment]
eb4a8ea latest commit to pull

**Comment by drtyhlpr** [comment]
wow thanks for the great pull. please split it up its all a big chaos.

- DROPBEAR
- IPTABLES fix
- VIRTUALBOX
- templates
- ubuntu?
- travis?

ps. thanks for adding rpi0,1 support but have you compiled and tested the generated images with all the supported rpi0,1 hardware?
pps. I do not like the info in the readme "about how to setup my build setup". this script was generated to run on a fresh debian out of the box (check and install missing deps and go)
pps. if travis CI is bs I will not include this. need to review but not mutch time

**Comment by burnbabyburn** [comment]
yeah i know its a huge mess :D 
I am using git first time in "production" and f*** up my branches. I assumed a pull equals to a freez. But apparently any further commits are included as well :/

**Comment by burnbabyburn** [comment]
ps. thanks for adding rpi0,1 support but have you compiled and tested the generated images with all the supported rpi0,1 hardware?
I did a test on RPI0W,RPI3,RPI3B+ i don't own any RPI1 device :/ I test RPI0W and it booted without kernel panics and i could login. I didn't test any further, because the RPI0W is in daily use :) I provided the RPI0 Image here:
```
https://www.dropbox.com/s/7udxwpi5gqk0v74/RPI-0W.img?dl=0
USER_NAME=pi
USER_PASSWORD=raspberry
PASSWORD=raspberry
```

**Pull request closed without merging**
