### PR TITLE
Add missing option -allow-unauthenticated to apt-get to allow use of …

### PR DESCRIPTION
**Pull request by JuergenKosel**
…apporx mirror

Signed-off-by: Juergen Kosel <juergen.kosel@gmx.de>

### CODE REVIEW

**Comment by justin-friel** [comment]
Hi,

I'm not sure if this commit is the right fix for the issue you are experiencing.

If you are seeing the error:
` W: GPG error: http://security.debian.org stretch/updates InRelease: Couldn't execute /usr/bin/apt-key to check /var/lib/apt/lists/partial/security.debian.org_dists_stretch_updates_InRelease` it is because of changes to apt in Debian Stretch.  

Apt now runs many operations, including apt-key as an unprivileged user, apt.  See [Possible backwards incompatible changes to APT](https://www.debian.org/releases/stretch/amd64/release-notes/ch-information.en.html#apt-issues) for more information.

Since the qemu-arm-static permissions are 744, only root can execute commands in the chroot.  This will cause apt to fail.  Please see drtyhlpr/rpi23-gen-image#85.
}#{issue_number}

If you are trying to use packages from a third-party repository, I would think the best rout would be to do so in a script in custom.d/.

Hope this helps,
Justin

**Comment by xtaran** [comment]
Please *don't*, independent of the reason. Adding `--allow-unauthenticated` opens a plethora of security holes. If `--allow-unauthenticated` seems necessary, either the local setup is broken, the remote repository is broken or there's a man-in-the-middle-attack (includes captive portals, etc.) going on.

**Comment by quozl** [comment]
Agreed.  I use an approx mirror too, and have fixed it using https://github.com/drtyhlpr/rpi23-gen-image/pull/85 ...

Easy mistake to make given the error message, but wrong idea to use `--allow-unauthenticated`, better is to fix the underlying problem, as it may have other impacts later.

**Comment by JuergenKosel** [comment]
I have not seen, that #85 already fixes the problem.

**Pull request closed without merging**
