### PR TITLE
Dropbear

### PR DESCRIPTION
**Pull request by burnbabyburn**
static ip in dropbear needs a tester. didn't noticed any error with dynamic ip 

- Enable dropbear in initramfs with cryptfs_cropbear=true
- dropbear initramfs supports static and dyn. ip - dropbear uses provided ip_config NET_*
- bluetooth with serial improved
- ipv6 legacy firewalling
- add cleanup to videocore
- improved apt-cacher-ng detection

### CODE REVIEW

**Comment by drtyhlpr** [comment]
wow great work again with this pull and the other! great new features etc. are both pulls ready to merge?

**Comment by burnbabyburn** [comment]
i'll have to add some fixes later. give me 'till the weekend :)

**Comment by drtyhlpr** [comment]
ok. great. I am about to add simple features 
ENABLE_SILENT=false, ENABLE_LOGO=true, ENABLE_SPLASH=true (cmdline.txt, config.txt) after the pull (to avoid any merge conflict bs) :)

**Comment by burnbabyburn** [comment]
if you merge #170 too, do it first as it may override some fixes here.

**Comment by drtyhlpr** [comment]
ok I still got some conflicts I had to solve. please verify files 15-rpi-config.sh, 21-firewall.sh and functions.sh. I can do some testing tomorrow evening cause bussy

**Pull request merged**
