### PR TITLE
Added ENABLE_DPHYSSWAP

### PR DESCRIPTION
**Pull request by BrainStone**
- This option allows the image to automatically enable swap. The size will be relative to the root partion
- Uses the `dphys-swapfile` package

### CODE REVIEW

**Comment by BrainStone** [comment]
Looking at #170 this might be a somewhat duplicate. Though having this as the default and the other option as an alternative would make sense, as this is really just a super simple plug'n'play solution.

**Comment by BrainStone** [comment]
This package is also what provides swap by default on Raspbian, so I think having this as the default and default enabled is the way to go.

**Comment by burnbabyburn** [comment]
`systemd-swap` is just a convinient and automatic way of managing swap, zram and zswap in one service. it's the default swapping service in e.g. arch

We don't have a service for "just" swap, but `systemd-swap` could be used as such.

- dphys-swapfile is a wrapper for swapon swapoff => static swap file
- systemd-swap => has dynamic swap file size

But setting swap as a default on SSD based systems isn't a good default in my opinion. I don't mind the disksmashing but swapping to a sdcard is slow af. (try to run FF with X) Also the default swapfile (created right after install - does this happen in chroot too?) is 1.5GB in size. This may be a huge filesize depending on the sd-card used.

ATM you can boot your system created with this script and let `iotop` run for an hour without noticing any writes. That's a nice default ;)

Maybe we could name it ENABLE_DPHYS_SWAP or ENABLE_DPHYSWAP to keep variable naming consinstent (ENABLE_SYSTEMDSWAP)

**Comment by burnbabyburn** [comment]
furthermore there is the possibility to add a swap partition on sdcard if ENABLE_SWAP is used. systemd creates a swap service if a swap partition is in /etc/fstab.

**Comment by BrainStone** [comment]
The nice thing about `dphys-swapfile` is that it does not create bloat in the image and resizes itself depending on the available space. And it highly depends on your SD card how fast/slow it is.  
While it can be slow, I think having a slow swap is better than having none. And I feel like there is a reason it is default on Raspbian. I believe the people making Raspbian know what they are doing.

And I agree, renaming to `ENABLE_DPHYSWAP` is better and I will do just that.

**Comment by drtyhlpr** [comment]
well this is how I think about swap space (in combination with sd cards):
https://www.raspberrypi.org/forums/viewtopic.php?t=2813

i ll take a look how we can simply integrate this feature.

please commit u follow up pulls to the testing branch of this project

**Comment by drtyhlpr** [comment]
is it rely needed to call
`systemctl restart dphys-swapfile`

on firstboot (rc) ?

because outherwise it would be great to just add the package to APT_INCLUDES.

```
if systemctl is-enabled dphys-swapfile ; then
  systemctl restart dphys-swapfile
fi
```
maybe this could just be added to the ende of https://github.com/drtyhlpr/rpi23-gen-image/blob/master/files/firstboot/22-expandroot.sh

**Comment by drtyhlpr** [comment]
I created a minimal pull that should work fine.

https://github.com/drtyhlpr/rpi23-gen-image/commit/958b7908f04797c1ba69f13c045907c0b70fac1f

**Pull request closed without merging**
